# Generated by Django 6.0.4 on 2026-04-25 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodproduct',
            name='calories',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='foodproduct',
            name='difficulty',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
