# Generated by Django 6.0.4 on 2026-04-24 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('ingredients_text', models.TextField(blank=True)),
                ('allergens_tags', models.TextField(blank=True)),
                ('nutriscore', models.CharField(blank=True, max_length=1)),
                ('sugars_100g', models.FloatField(default=0)),
                ('salt_100g', models.FloatField(default=0)),
                ('image_url', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='HealthConstraint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='health_constraints',
            field=models.ManyToManyField(blank=True, to='accounts.healthconstraint'),
        ),
    ]
