# Generated by Django 6.0.4 on 2026-04-26 22:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_foodproduct_calories_foodproduct_difficulty'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodproduct',
            name='favorites',
            field=models.ManyToManyField(blank=True, related_name='favorite_products', to=settings.AUTH_USER_MODEL),
        ),
    ]
