# Generated by Django 6.0.4 on 2026-04-24 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_foodproduct_healthconstraint_user_health_constraints'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodproduct',
            name='category',
            field=models.CharField(default='sale', max_length=50),
        ),
    ]
