# Generated by Codex on 2026-04-27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_age_user_aliments_a_eviter_user_culinary_level_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="""
                    ALTER TABLE accounts_user
                    ADD COLUMN IF NOT EXISTS activity_level varchar(20) NOT NULL DEFAULT 'moderate';
                    """,
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
            state_operations=[
                migrations.AddField(
                    model_name='user',
                    name='activity_level',
                    field=models.CharField(
                        blank=True,
                        choices=[
                            ('sedentary', 'Sedentaire'),
                            ('light', 'Legere'),
                            ('moderate', 'Moderee'),
                            ('active', 'Active'),
                            ('very_active', 'Tres active'),
                        ],
                        default='moderate',
                        max_length=20,
                    ),
                ),
            ],
        ),
    ]
