# Generated by Django 6.0.4 on 2026-09-30 19:20

import accounts.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_encrypt_sensitive_profile_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodproduct',
            name='calories',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='foodproduct',
            name='category',
            field=models.CharField(choices=[('sale', 'Sale'), ('sucre', 'Sucre'), ('healthy', 'Healthy'), ('vegan', 'Vegan')], db_index=True, default='sale', max_length=50),
        ),
        migrations.AlterField(
            model_name='foodproduct',
            name='difficulty',
            field=models.CharField(blank=True, choices=[('easy', 'Facile'), ('medium', 'Modere'), ('hard', 'Complexe')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='foodproduct',
            name='name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='activity_level',
            field=models.CharField(blank=True, default='moderate', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='aliments_a_eviter',
            field=accounts.fields.EncryptedTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='health_constraints_snapshot',
            field=accounts.fields.EncryptedTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='restrictions',
            field=accounts.fields.EncryptedTextField(blank=True),
        ),
    ]
